/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.service.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rcs.service.model.ChatRoom;
import com.rcs.service.model.ChatRoomModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the ChatRoom service. Represents a row in the &quot;VideoChat_ChatRoom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rcs.service.model.ChatRoomModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChatRoomImpl}.
 * </p>
 *
 * @author flor
 * @see ChatRoomImpl
 * @see com.rcs.service.model.ChatRoom
 * @see com.rcs.service.model.ChatRoomModel
 * @generated
 */
public class ChatRoomModelImpl extends BaseModelImpl<ChatRoom>
	implements ChatRoomModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chat room model instance should use the {@link com.rcs.service.model.ChatRoom} interface instead.
	 */
	public static final String TABLE_NAME = "VideoChat_ChatRoom";
	public static final Object[][] TABLE_COLUMNS = {
			{ "chatRoomId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "sessionId", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table VideoChat_ChatRoom (chatRoomId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,sessionId VARCHAR(255) null,name VARCHAR(75) null,description VARCHAR(255) null)";
	public static final String TABLE_SQL_DROP = "drop table VideoChat_ChatRoom";
	public static final String ORDER_BY_JPQL = " ORDER BY chatRoom.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VideoChat_ChatRoom.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rcs.service.model.ChatRoom"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rcs.service.model.ChatRoom"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rcs.service.model.ChatRoom"));

	public ChatRoomModelImpl() {
	}

	public long getPrimaryKey() {
		return _chatRoomId;
	}

	public void setPrimaryKey(long primaryKey) {
		setChatRoomId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_chatRoomId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ChatRoom.class;
	}

	public String getModelClassName() {
		return ChatRoom.class.getName();
	}

	public long getChatRoomId() {
		return _chatRoomId;
	}

	public void setChatRoomId(long chatRoomId) {
		_chatRoomId = chatRoomId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public String getSessionId() {
		if (_sessionId == null) {
			return StringPool.BLANK;
		}
		else {
			return _sessionId;
		}
	}

	public void setSessionId(String sessionId) {
		_sessionId = sessionId;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public ChatRoom toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ChatRoom)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					ChatRoom.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		ChatRoomImpl chatRoomImpl = new ChatRoomImpl();

		chatRoomImpl.setChatRoomId(getChatRoomId());
		chatRoomImpl.setGroupId(getGroupId());
		chatRoomImpl.setCompanyId(getCompanyId());
		chatRoomImpl.setUserId(getUserId());
		chatRoomImpl.setUserName(getUserName());
		chatRoomImpl.setCreateDate(getCreateDate());
		chatRoomImpl.setModifiedDate(getModifiedDate());
		chatRoomImpl.setSessionId(getSessionId());
		chatRoomImpl.setName(getName());
		chatRoomImpl.setDescription(getDescription());

		chatRoomImpl.resetOriginalValues();

		return chatRoomImpl;
	}

	public int compareTo(ChatRoom chatRoom) {
		int value = 0;

		value = getName().compareTo(chatRoom.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ChatRoom chatRoom = null;

		try {
			chatRoom = (ChatRoom)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = chatRoom.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ChatRoom> toCacheModel() {
		ChatRoomCacheModel chatRoomCacheModel = new ChatRoomCacheModel();

		chatRoomCacheModel.chatRoomId = getChatRoomId();

		chatRoomCacheModel.groupId = getGroupId();

		chatRoomCacheModel.companyId = getCompanyId();

		chatRoomCacheModel.userId = getUserId();

		chatRoomCacheModel.userName = getUserName();

		String userName = chatRoomCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			chatRoomCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			chatRoomCacheModel.createDate = createDate.getTime();
		}
		else {
			chatRoomCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			chatRoomCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			chatRoomCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		chatRoomCacheModel.sessionId = getSessionId();

		String sessionId = chatRoomCacheModel.sessionId;

		if ((sessionId != null) && (sessionId.length() == 0)) {
			chatRoomCacheModel.sessionId = null;
		}

		chatRoomCacheModel.name = getName();

		String name = chatRoomCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			chatRoomCacheModel.name = null;
		}

		chatRoomCacheModel.description = getDescription();

		String description = chatRoomCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			chatRoomCacheModel.description = null;
		}

		return chatRoomCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{chatRoomId=");
		sb.append(getChatRoomId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", sessionId=");
		sb.append(getSessionId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.rcs.service.model.ChatRoom");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>chatRoomId</column-name><column-value><![CDATA[");
		sb.append(getChatRoomId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sessionId</column-name><column-value><![CDATA[");
		sb.append(getSessionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ChatRoom.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ChatRoom.class
		};
	private long _chatRoomId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _sessionId;
	private String _name;
	private String _description;
	private transient ExpandoBridge _expandoBridge;
	private ChatRoom _escapedModelProxy;
}