/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.rcs.service.service.persistence.ChatRoomGroupPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ChatRoomGroup service. Represents a row in the &quot;VideoChat_ChatRoomGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rcs.service.model.impl.ChatRoomGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rcs.service.model.impl.ChatRoomGroupImpl}.
 * </p>
 *
 * @author flor
 * @see ChatRoomGroup
 * @see com.rcs.service.model.impl.ChatRoomGroupImpl
 * @see com.rcs.service.model.impl.ChatRoomGroupModelImpl
 * @generated
 */
public interface ChatRoomGroupModel extends BaseModel<ChatRoomGroup>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chat room group model instance should use the {@link ChatRoomGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this chat room group.
	 *
	 * @return the primary key of this chat room group
	 */
	public ChatRoomGroupPK getPrimaryKey();

	/**
	 * Sets the primary key of this chat room group.
	 *
	 * @param primaryKey the primary key of this chat room group
	 */
	public void setPrimaryKey(ChatRoomGroupPK primaryKey);

	/**
	 * Returns the chat room ID of this chat room group.
	 *
	 * @return the chat room ID of this chat room group
	 */
	public long getChatRoomId();

	/**
	 * Sets the chat room ID of this chat room group.
	 *
	 * @param chatRoomId the chat room ID of this chat room group
	 */
	public void setChatRoomId(long chatRoomId);

	/**
	 * Returns the chat room group ID of this chat room group.
	 *
	 * @return the chat room group ID of this chat room group
	 */
	public long getChatRoomGroupId();

	/**
	 * Sets the chat room group ID of this chat room group.
	 *
	 * @param chatRoomGroupId the chat room group ID of this chat room group
	 */
	public void setChatRoomGroupId(long chatRoomGroupId);

	/**
	 * Returns the group ID of this chat room group.
	 *
	 * @return the group ID of this chat room group
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this chat room group.
	 *
	 * @param groupId the group ID of this chat room group
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this chat room group.
	 *
	 * @return the company ID of this chat room group
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this chat room group.
	 *
	 * @param companyId the company ID of this chat room group
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this chat room group.
	 *
	 * @return the user ID of this chat room group
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this chat room group.
	 *
	 * @param userId the user ID of this chat room group
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this chat room group.
	 *
	 * @return the user uuid of this chat room group
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this chat room group.
	 *
	 * @param userUuid the user uuid of this chat room group
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this chat room group.
	 *
	 * @return the user name of this chat room group
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this chat room group.
	 *
	 * @param userName the user name of this chat room group
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this chat room group.
	 *
	 * @return the create date of this chat room group
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this chat room group.
	 *
	 * @param createDate the create date of this chat room group
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this chat room group.
	 *
	 * @return the modified date of this chat room group
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this chat room group.
	 *
	 * @param modifiedDate the modified date of this chat room group
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type of this chat room group.
	 *
	 * @return the type of this chat room group
	 */
	public int getType();

	/**
	 * Sets the type of this chat room group.
	 *
	 * @param type the type of this chat room group
	 */
	public void setType(int type);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ChatRoomGroup chatRoomGroup);

	public int hashCode();

	public CacheModel<ChatRoomGroup> toCacheModel();

	public ChatRoomGroup toEscapedModel();

	public String toString();

	public String toXmlString();
}