/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rcs.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ChatRoom service. Represents a row in the &quot;VideoChat_ChatRoom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rcs.service.model.impl.ChatRoomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rcs.service.model.impl.ChatRoomImpl}.
 * </p>
 *
 * @author flor
 * @see ChatRoom
 * @see com.rcs.service.model.impl.ChatRoomImpl
 * @see com.rcs.service.model.impl.ChatRoomModelImpl
 * @generated
 */
public interface ChatRoomModel extends BaseModel<ChatRoom>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chat room model instance should use the {@link ChatRoom} interface instead.
	 */

	/**
	 * Returns the primary key of this chat room.
	 *
	 * @return the primary key of this chat room
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chat room.
	 *
	 * @param primaryKey the primary key of this chat room
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the chat room ID of this chat room.
	 *
	 * @return the chat room ID of this chat room
	 */
	public long getChatRoomId();

	/**
	 * Sets the chat room ID of this chat room.
	 *
	 * @param chatRoomId the chat room ID of this chat room
	 */
	public void setChatRoomId(long chatRoomId);

	/**
	 * Returns the group ID of this chat room.
	 *
	 * @return the group ID of this chat room
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this chat room.
	 *
	 * @param groupId the group ID of this chat room
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this chat room.
	 *
	 * @return the company ID of this chat room
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this chat room.
	 *
	 * @param companyId the company ID of this chat room
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this chat room.
	 *
	 * @return the user ID of this chat room
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this chat room.
	 *
	 * @param userId the user ID of this chat room
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this chat room.
	 *
	 * @return the user uuid of this chat room
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this chat room.
	 *
	 * @param userUuid the user uuid of this chat room
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this chat room.
	 *
	 * @return the user name of this chat room
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this chat room.
	 *
	 * @param userName the user name of this chat room
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this chat room.
	 *
	 * @return the create date of this chat room
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this chat room.
	 *
	 * @param createDate the create date of this chat room
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this chat room.
	 *
	 * @return the modified date of this chat room
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this chat room.
	 *
	 * @param modifiedDate the modified date of this chat room
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the session ID of this chat room.
	 *
	 * @return the session ID of this chat room
	 */
	@AutoEscape
	public String getSessionId();

	/**
	 * Sets the session ID of this chat room.
	 *
	 * @param sessionId the session ID of this chat room
	 */
	public void setSessionId(String sessionId);

	/**
	 * Returns the name of this chat room.
	 *
	 * @return the name of this chat room
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this chat room.
	 *
	 * @param name the name of this chat room
	 */
	public void setName(String name);

	/**
	 * Returns the description of this chat room.
	 *
	 * @return the description of this chat room
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this chat room.
	 *
	 * @param description the description of this chat room
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ChatRoom chatRoom);

	public int hashCode();

	public CacheModel<ChatRoom> toCacheModel();

	public ChatRoom toEscapedModel();

	public String toString();

	public String toXmlString();
}